import * as CONST from "../../src/appConstants";


// mocks the full list of entries we get from the database:
export const mockFullDataList = [
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'blue',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Cobra',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '1991',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'New York',
        [CONST.DATA_ITEM_PROPERTY.COST]: '5319'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'red',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Diablo',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '1997',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'San Francisco',
        [CONST.DATA_ITEM_PROPERTY.COST]: '2335'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'yellow',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Prius',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '1999',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'San Francisco',
        [CONST.DATA_ITEM_PROPERTY.COST]: '302'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'crimson',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Taurus',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '1982',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'Chicago',
        [CONST.DATA_ITEM_PROPERTY.COST]: '112'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'black',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'E Series',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '1979',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'Moscow',
        [CONST.DATA_ITEM_PROPERTY.COST]: '789'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'white',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Accord',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '2012',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'St. Petersburg',
        [CONST.DATA_ITEM_PROPERTY.COST]: '917'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'white',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Civic',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '2004',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'Delhi',
        [CONST.DATA_ITEM_PROPERTY.COST]: '1343'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'light blue',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Roadster',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '2008',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'Mumbai',
        [CONST.DATA_ITEM_PROPERTY.COST]: '3129'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'silver',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Sonata',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '2012',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'Beijing',
        [CONST.DATA_ITEM_PROPERTY.COST]: '2108'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'black',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Prius',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '2014',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'Shanghai',
        [CONST.DATA_ITEM_PROPERTY.COST]: '431'
    },
    {
        [CONST.DATA_ITEM_PROPERTY.CAR_COLOR]: 'orange',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL]: 'Taurus',
        [CONST.DATA_ITEM_PROPERTY.CAR_MODEL_YEAR]: '2000',
        [CONST.DATA_ITEM_PROPERTY.LOCATION]: 'Chennai',
        [CONST.DATA_ITEM_PROPERTY.COST]: '3500'
    }
];